---
name: Question
description: General questions about our services
labels: ["question"]
body:
  - type: textarea
    attributes:
      label: Question
      description: What would you like to know?
      placeholder: Ask your question...
    validations:
      required: true
